<?xml version="1.0"?>
<package format="3">
    <name>rover_shared_libs</name>
    <version>1.0.0</version>
    <description>Rover shared libraries</description>
    <maintainer email="save1403@usherbrooke.ca">you</maintainer>
    <license>MIT</license>

    <buildtool_depend>ament_cmake</buildtool_depend>
    <depend>rclcpp</depend>
    <depend>rover_msgs</depend>

    <export>
        <build_type>ament_cmake</build_type>
    </export>
</package>